@startuml

autonumber 10

Alice -> Bob: Hello
note right
    The <U+0025>autonumber<U+0025> works everywhere
    Here its value is ** %autonumber% **
end note

Alice <-- Bob: Hello, thanks, // This is response number %autonumber%

@enduml